### ISSUE TITLE
goto, press, and click all throw ipc.timeout.send

### ISSUE THREAD

**Issue by gsidsid** [replac5/electron-puppeteer#2]
Trying to use this with a vue project- is there anything that might be causing ipc messages to timeout? I am running the demo code and the following in Nuxt's lifecycle method:

`mounted() {
    this.$nextTick(() => {
      run(); // demo code async run method
    });
  },`

Getting "ipc.timeout.send" errors. It seems to load the first page (if using createPage), but cannot navigate or do anything. Setting zoom functions and devtools on the webview are working, however.

**Comment by gsidsid** [comment]
Not sure if it is of importance but the UUID is '~' and the message is exactly as follows:

`Uncaught (in promise) ipc.timeout.send: elementHandle.press@~, payload: {"selector":["document","#searchBox"],"keyCode":69,"text":"e"}`

Favicons also do not seem to appear

**Comment by xujian0921** [comment]
我也遇到了这个问题，有解决方案吗

**Comment by replace5** [comment]
@gsidsid @xujian0921 maybe upgrade to 1.1.1 will resolved
